site_name: Go Tour go教程
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- 简介: 'index.md'
- Go基础:
  - 'Hello Go!': 'basics/00_hello_go/hello_go.md'
  - 'Go 基础类型': 'basics/01_go_basic_types/basic_types.md'
  - 'Go 数组和切片': 'basics/02_go_array_and_slice/array_and_slice.md'
  - 'Go 映射': 'basics/03_map/map.md'
  - 'Go 控制流语句': 'basics/04_go_control_flow/go_procedural.md'